server:
  port: 8102
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'