server:
  port: 8905

spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gbtyy/springcloud-config.git
          username: gbtyy
          password: gbtyygaotao123
          clone-on-start: true
  security:
    user:
      name: root
      password: 123456
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka