server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: root
      password: root

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhsot
