server:
  port: 8002

spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://replica2:8003/eureka/
  instance:
    hostname: replica1

management:
  endpoints:
    web:
      exposure:
        include: '*'